### ISSUE TITLE
New Fortran code for serial sorting character arrays, and parallelizing SP, DP, and character arrays

### ISSUE THREAD

**Issue by OCsteve** [cphyc/Fortran-parallel-sort#1]
New Fortran code for serial sorting character arrays, and parallelizing SP, DP, and character arrays. Four more routines created, for a total of eight routines. Overloaded the user interface so that a call to Parallel_Sort(A, order) will handle array A of type: integer, real(4), real(8), or character(:).

**Comment by cphyc** [comment]
Thanks for the contribution! This all look great, minor some concerns about file names and nits in the tests.

**Comment by cphyc** [comment]
I have closed your PRs and included them in #5. Please tell me if this is fine for you!

**Comment by OCsteve** [comment]
Hi Corentin,

I’m on vacation now but will make all of the minor changes you suggested on Monday. I’m a newbie with making GitHub PRs so I experienced some problems. Initially I did try to upload the files with the same names but the New PR request button was grayed out so I did a workaround to get the files uploaded.

Have a great weekend,
Steve

**Comment by OCsteve** [comment]
And closing the PRs and putting them in #5 sounds fine with me.

**Comment by OCsteve** [comment]
Hi Corentin,

 

I reviewed all the enhancements you made and think they are great. The timing benchmarks are a nice touch. We make a good team. :) Being new to the GitHub process I’m not sure if I need to officially do anything more to approve the changes.

 

I’ve been coding in Fortran for nearly 40 years on a daily basis, and also program in python and a dozen other languages over the years. Fortran has always been my favorite. It still remains a mystery to me why Fortran is one of the very few languages that does not have an intrinsic sorting subroutine, either serial or parallel. Maybe the Fortran standards committees could use our code as a baseline and users could always create their own algorithms to either privately or publicly improve on our code base.

 

Best regards,

Steve

**Comment by cphyc** [comment]
Cheers, I'll merge the changes then! If you feel like submitting the code to the Fortran stdlib (https://github.com/fortran-lang/stdlib) or registering to the fpm registry, I'd be happy to!

**Comment by OCsteve** [comment]
Excellent! I’m good with you submitting our code base to the Fortran stdlib but leave that decision up to you.

 

Cheers,

Steve

**Comment by OCsteve** [comment]
Hi Corentin,

 

I was implementing our code in some of my programs and found a minor bug. On an 8-core computer with an array size of 7,  both chunk and chunk2 are zero. Chunk2 results in a divide-by-zero error. I created simple code to handle this trivial case. I created an issue and uploaded the code. I’m still not sure if I did this part of the GitHub process correctly but at any rate the code is there. Also I re-used the existing merge sort which could be replaced with an insertion sort, etc.

 

Regards,

Steve

 

From: Steve Rivkin ***@***.*** 
Sent: Tuesday, June 08, 2021 9:19 AM
To: 'cphyc/Fortran-parallel-sort' ***@***.***>; 'cphyc/Fortran-parallel-sort' ***@***.***>
Cc: 'Author' ***@***.***>
Subject: RE: [cphyc/Fortran-parallel-sort] New Fortran code for serial sorting character arrays, and parallelizing SP, DP, and character arrays (#1)

 

Excellent! I’m good with you submitting our code base to the Fortran stdlib but leave that decision up to you.

 

Cheers,

Steve
